Implement test cases for search (#10193)
* Move search folder to logic

* Add testEmptyLibrarySearch

* Add initializeDatabaseFromPath

* Add TestLibraryA & testUpperAndLowerWordSearch

* Add testSimpleSingleFieldSearch

* Add testSimpleMultipleFieldSearch

* Add testSensitiveWordSearch

* Add testSensitiveMutipleFieldSearch

* Add BibEntries for test-library-B

* Add testSimpleRegularExpression

* Add testSensitiveRegularExpression

* SimplePDFFulltextSearch WIP

* Change set.Files to add.File

* Add testSimplePDFNoteFulltextSearch WIP

* Move indexer

* Add missing @Tests to SearchFunctionalityTest.java WIP

* WIP

* Exclude non-functional @Tests

* Add withFiles

* Remove empty lines

* @NullMarked for LinkedFile

* Fix Logger parameter

* Streamline tests

* Fix checkstyle

* Refine tests

* Get rid of missing "identity" formatter

* Minimize test files

* Remove obsolete method (and make indexer class variable to speedup)

* Fix filenames

* Some refactorings

* Revert global indexer mapping (does not work)

ERROR: Could not retrieve search results.: org.apache.lucene.index.IndexNotFoundException: no segments* file found in NIOFSDirectory@C:\Users\koppor\AppData\Local\Temp\junit11457118934853053051 lockFactory=org.apache.lucene.store.NativeFSLockFactory@5d6751d7: files: [write.lock]

* Revert "Revert global indexer mapping (does not work)"

This reverts commit e0810441971ad7d456683903ce9bb7d0fbeb729e.

* Small code updates

* Rename test files

* Some more logging

* Refine transaction boundaries (and some minor tweaks)

* Add TODO

* Fix off-by-one error

* Remove non-used .bib file

* Refine comments

* Fix variable assignment

* test-library-A -> test-library-title-casing

* Merge test cases of library-B.bib into title-casing.bib

* Increase transaction boundary for index addition/removal

* More readable directory names for index directory

* WIP: Introduce PdfIndexerManager

* Preparation for "fulltext search not checking all attached files upon start"

* Use "right" factory (and rename factor getter)

* Fix FullTextSeachRule (refactoring introduced a bug)

* Revert property for recheck of attached files

* Fix linting issues

* Fix Formatters optimization

* Fix test

* Exception for architecture

* Refine .gitignore

* Add missing }

* Do not search for PDF files in case of an exception of a search

* Remove duplicate code (and unneccsary pre-fetch of search results)

* Add exception for test

* Remove ".getMessage()"

* Move comment and remove obsolete variable

* Fix typo

* Fix name

* Add dot

* Add comment

* Call splitting method

* Add JavaDocComment

* Revert lambdas

---------

Co-authored-by: Oliver Kopp <kopp.dev@gmail.com>