Removed unused method
Fixes src\main\java\org\jabref\model\bibtexkeypattern\AbstractBibtexKeyPattern.java:60: error: [CollectionIncompatibleType] Argument 'type' should not be passed to this method; its type String is not compatible with its collection's type argument EntryType
        data.remove(type);
                   ^
    (see https://errorprone.info/bugpattern/CollectionIncompatibleType)