Fix Russian translation
Should fix this bug when select Russian translation
```
java.lang.IllegalStateException: It is not allowed that the toReplace string: '<tt>author=smith and title=electrical</tt>' does not exist in the original string
	at org.jabref.gui.util.TooltipTextUtil.splitReplace(TooltipTextUtil.java:92)
	at org.jabref.gui.util.TooltipTextUtil.formatToTexts(TooltipTextUtil.java:62)
	at org.jabref.gui.search.GlobalSearchBar.setHintTooltip(GlobalSearchBar.java:291)
...
```