Fix closing of JabRef in case of issues with index writer (#10840)
* Fix closing of JabRef in case of issues with index writer

Uncaught exception occurred in Thread[#60,JavaFX Application Thread,5,main]
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.close()" because "this.indexWriter" is null
	at org.jabref@100.0.0/org.jabref.logic.pdf.search.PdfIndexer.close(PdfIndexer.java:299)
	at org.jabref@100.0.0/org.jabref.logic.pdf.search.PdfIndexerManager.shutdownIndexer(PdfIndexerManager.java:74)
	at org.jabref@100.0.0/org.jabref.gui.LibraryTab.onClosed(LibraryTab.java:792)

* NPEs are caught at onClosed

* Handle absent index writer

* Try to handle null directory

* Discard changes to src/main/java/org/jabref/gui/LibraryTab.java

* Use java.io.tempDir

* Add comments and annotations